// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreamAPI.Models;

namespace ScreamAPI.Migrations
{
    [DbContext(typeof(ScreenContext))]
    [Migration("20201116220816_Adicionado exclusão lógica")]
    partial class Adicionadoexclusãológica
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ScreamAPI.Models.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_imagem")
                        .UseIdentityColumn();

                    b.Property<string>("ArquivoImagem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("arq_imagem");

                    b.Property<bool>("ExclusaoImagem")
                        .HasColumnType("bit")
                        .HasColumnName("ex_imagem");

                    b.Property<string>("NomeImagem")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nm_imagem");

                    b.HasKey("IdImagem");

                    b.ToTable("Tb_Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
